name: davidkhala.data.format
on: push
jobs:
  avro-n-parquet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          tests: format/tests
          test-entry-point: pytest
          working-directory: format