name: davidkhala.data
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          tests: format/tests
          test-entry-point: pytest
          working-directory: format
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
  frame:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          tests: frame/tests
          test-entry-point: pytest
          working-directory: frame